packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  "next": "15.1.6"
  "next-themes": "^0.4.4"
  "react": "19.0.0"
  "react-day-picker": "^9.5.1"
  "react-dom": "19.0.0"
  "react-hook-form": "^7.54.2"
  "react-resizable-panels": "^2.1.7"
  "@tailwindcss/postcss": "^4.0.5"
  "tailwind-merge": "^3.0.1"
  tailwindcss: "^4.0.5"
  tailwindcss-animate: "^1.0.7"
  tailwind-variants: "^0.1.14"
  "@types/node": "^22.13.1"
  "@types/react": "19.0.8"
  "@types/react-dom": "19.0.3"
  "postcss": "^8.5.1"
  "prettier": "^3.4.2"
  "prettier-plugin-tailwindcss": "^0.6.11"
  "typescript": "^5.7.3"
  "typescript-eslint": "^8.23.0"
  "class-variance-authority": "^0.7.1"
  "clsx": "^2.1.1"
  "cmdk": "^1.0.4"
  "@tabler/icons-react": "^3.24.0"
  "next-international": "^1.2.4"
  "next-safe-action": "^7.10.3"
  "@next/third-parties": "^15.1.0"
  "nuqs": "^2.3.2"
  "date-fns": "^4.1.0"
  "@svgr/webpack": "^8.1.0"
  "cookies-next": "^5.1.0"
  "next-auth": "^4.24.11"
  "@tanstack/react-query": "^5.66.0"
  "@tanstack/react-table": "^8.20.6"
  "@tanstack/react-query-devtools": "^5.66.0"
  "framer-motion": "^12.6.3"
  "motion": "^12.6.5"
  

