blank_issues_enabled: true
contact_links:
  - name: 💡 Feature Request
    url: https://links.raizora.com/feature-request
    about: Please submit feature requests here.
  - name: 🛟 Support
    url: https://help.raizora.com
    about: Join us on Discord to ask support questions.