http:
  middlewares:
    # Middleware for security config
    secureHeaders:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

  # Konfigurasi TLS global
  # tls:
  #   options:
  #     default:
  #       minVersion: VersionTLS12
  #       cipherSuites:
  #         - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  #         - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  #         - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305